"""initial schema

Revision ID: 78d2dd3b32c9
Revises: 
Create Date: 2026-04-16 16:37:25.859164

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78d2dd3b32c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccmd',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aor_type', sa.Enum('GEOGRAPHIC', 'FUNCTIONAL', name='aortype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_tier', sa.Integer(), nullable=False),
    sa.Column('state_affiliation', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_name'), ['name'], unique=True)

    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('classification_marking', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('handling_caveat', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dissemination_controls', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('source_reliability', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('info_credibility', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_article_url')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index('ix_article_published_at', ['published_at'], unique=False)

    op.create_table('ingest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('articles_seen', sa.Integer(), nullable=False),
    sa.Column('articles_new', sa.Integer(), nullable=False),
    sa.Column('raw_feed_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_run_feed_id'), ['feed_id'], unique=False)

    op.create_table('analyst_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('observation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('significance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recommended_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_taken', sa.Enum('REVIEWED', 'FLAGGED_FOR_OIC', 'DISMISSED', 'ESCALATED', name='analystaction'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyst_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_note_analyst_id'), ['analyst_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_note_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_note_article_created', ['article_id', 'created_at'], unique=False)

    op.create_table('article_ccmd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('ccmd_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('matched_terms', sa.JSON(), nullable=True),
    sa.Column('tagged_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('tagged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['ccmd_code'], ['ccmd.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'ccmd_code', name='uq_article_ccmd')
    )
    with op.batch_alter_table('article_ccmd', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_ccmd_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_ccmd_ccmd_code'), ['ccmd_code'], unique=False)

    op.create_table('mdm_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.Column('classifier_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('verifiable_claims', sa.JSON(), nullable=True),
    sa.Column('emotional_language', sa.JSON(), nullable=True),
    sa.Column('logical_fallacies', sa.JSON(), nullable=True),
    sa.Column('unsourced_assertions', sa.JSON(), nullable=True),
    sa.Column('temporal_claims', sa.JSON(), nullable=True),
    sa.Column('source_transparency_score', sa.Integer(), nullable=True),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('corroborating_article_ids', sa.JSON(), nullable=True),
    sa.Column('concern_score', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('LIKELY_RELIABLE', 'REQUIRES_VERIFICATION', 'SIGNIFICANT_CONCERNS', 'HIGH_CONCERN', 'INSUFFICIENT_DATA', name='mdmcategory'), nullable=False),
    sa.Column('reasoning_breakdown', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mdm_assessment', schema=None) as batch_op:
        batch_op.create_index('ix_mdm_article_assessed_at', ['article_id', 'assessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mdm_assessment_article_id'), ['article_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mdm_assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mdm_assessment_article_id'))
        batch_op.drop_index('ix_mdm_article_assessed_at')

    op.drop_table('mdm_assessment')
    with op.batch_alter_table('article_ccmd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_ccmd_ccmd_code'))
        batch_op.drop_index(batch_op.f('ix_article_ccmd_article_id'))

    op.drop_table('article_ccmd')
    with op.batch_alter_table('analyst_note', schema=None) as batch_op:
        batch_op.drop_index('ix_note_article_created')
        batch_op.drop_index(batch_op.f('ix_analyst_note_article_id'))
        batch_op.drop_index(batch_op.f('ix_analyst_note_analyst_id'))

    op.drop_table('analyst_note')
    with op.batch_alter_table('ingest_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_run_feed_id'))

    op.drop_table('ingest_run')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index('ix_article_published_at')
        batch_op.drop_index(batch_op.f('ix_article_feed_id'))
        batch_op.drop_index(batch_op.f('ix_article_content_hash'))

    op.drop_table('article')
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_name'))

    op.drop_table('feed')
    op.drop_table('ccmd')
    # ### end Alembic commands ###
